/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hacktonfuckjackson;

import java.io.File;
import javax.swing.JFileChooser;
import org.bitcoinj.crypto.TransactionSignature;
import org.p2p.solanaj.rpc.RpcClient;
import org.p2p.solanaj.programs.SystemProgram;
import org.p2p.solanaj.core.Transaction;
import org.p2p.solanaj.core.PublicKey;


/**
 *
 * @author Loh Kai Xuan
 */
public class Upload extends javax.swing.JFrame {
    /**
     * Creates new form Upload
     */
    public Upload() {
        initComponents();
        Login login = new Login();
        String role = login.getSaveRole();        
        //JOptionPane.showMessageDialog(null, role);
        if(role.equals("User")){
            btnregister.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        btnupload = new javax.swing.JButton();
        btnsend = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        btnupload.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnupload.setText("Upload");
        btnupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuploadActionPerformed(evt);
            }
        });

        btnsend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsend.setText("Send");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        btnregister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnregister)
                        .addGap(18, 18, 18)
                        .addComponent(btnupload, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsend, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupload)
                    .addComponent(btnsend)
                    .addComponent(btnregister))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename =f.getAbsolutePath();
        txtarea.setText(filename);
    }//GEN-LAST:event_btnuploadActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
       Admin admin = new Admin();
       admin.show();
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        //wallet sol = new wallet();
        //String privatekey = sol.getSavePrivateKey();
        //String publickey = sol.getSavePublicKey();
        
        //String senderPublicKey = "7REmDwxr3xEUdzCiUsPZwfzuNbCMX6RScKA2FzNzDnzL";
        //String recipientPublicKey = "2LXL8QDnAVBeA6pAHDUwaVb9h8pmrn53z2GuXb8CbHMQ";
        /*try {
            String publicKeystring = "7REmDwxr3xEUdzCiUsPZwfzuNbCMX6RScKA2FzNzDnzL";
            //byte[] publicKeybyte = publicKeystring.getBytes();
            PublicKey senderPublicKey = new PublicKey(publicKeystring);
        } catch (Exception e) {        }
        try {
            String publicKeystring2 = "2LXL8QDnAVBeA6pAHDUwaVb9h8pmrn53z2GuXb8CbHMQ";
            //byte[] publicKeybyte2 = publicKeystring2.getBytes();
            PublicKey recipientPublicKey = new PublicKey(publicKeystring2);
        } catch (Exception e) {        }
        long lamports =100; //0.0000001 Solana in Lamports        
        Transaction transaction = new Transaction();
        transaction.addInstruction(SystemProgram.transfer(senderPublicKey,recipientPublicKey,lamports));
        */
    }//GEN-LAST:event_btnsendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregister;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnupload;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
